require'fileutils'
require'../include.rb'

# Variables
# -----------------------------
$AS65	=	'xa'
$CC		=	'cc'
$OBJS	=	'nes.nes asciitest.nes vram.nes'

$stdout_mutex=Mutex.new

# Rules
# -----------------------------
task :default do
	make $OBJS.split
end

task :clean do
	clean $OBJS.split
end

task :sim65 do
	# Setup execution environment to use wxWidgets 2.8
	`set -x; export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`
	#`./sim65`
end
