require'fileutils'
require'./include.rb'

# Variables
# -----------------------------
$AS65			=	'xa'
$CC				=	'cc'
$CFLAGS			=	'-Wfatal-errors `pkg-config --cflags portaudio-2.0`'
$LDFLAGS		=	'-lncurses -pthread -lpthread `pkg-config --libs portaudio-2.0`'
$OBJS			=	'cpu.o ram.o rom.o joy.o'
$LIB			=	'lib65.a'

if Gem.win_platform?
	# Cygwin
	$SDL2_CFLAGS	= '-DSDL_MAIN_HANDLED -I/mingw64/include'
	$SDL2_LDFLAGS	= '-L/mingw64/lib -lSDL2main -lSDL2'
else
	# Linux/Mac/Unix
	$SDL2_CFLAGS	=	'`pkg-config --cflags sdl2`'
	$SDL2_LDFLAGS	=	'`pkg-config --libs sdl2`'
end

$stdout_mutex=Mutex.new

# Rules
# -----------------------------

task :all => [:default] do
end

task :default => [:_65db, :_65da, :_fes, :test] do
	
end

task :lib65 => [:objs] do
	thread_print"  AR\tlib65.a"
	`ar mc lib65.a #{$OBJS}`
end

task :_65db => [:lib65] do
	thread_print"  CC\t65db"
	`cc -o 65db #{$CFLAGS} 65db.c 65db_disasm.c lib65.a #{$LDFLAGS}`
end

task :_65da => [:lib65] do
	thread_print"  CC\t65da"
	`cc -o 65da #{$CFLAGS} 65da.c 65da_disasm.c lib65.a #{$LDFLAGS}`
end

task :_fes => [:objs] do
	thread_print"  CC\tfes"
	`cc -o fes #{$CFLAGS} #{$SDL2_CFLAGS} fes.c ppu.c sdl.c pa.c lib65.a #{$LDFLAGS} #{$SDL2_LDFLAGS}`
end

task :test do
	thread_print'Entering directory test'
	thread_print`cd test; rake`
	thread_print'Leaving directory test'
end

task :objs do
	make $OBJS.split
end

task :clean do
	clean '65db 65da fes lib65.a *.o test/*.nes'.split
end
